### ISSUE TITLE
Suggested Code Change

### ISSUE THREAD

**Issue by cyberblitz** [MariyaSha/SimpleSMSspamFilter_GUI#2]
Below is my suggested change to the code. Saves Code duplication. Let the code work for you not the other way around :)

I'm enjoying your lessons, good work :)

![image](https://user-images.githubusercontent.com/42084666/107580152-df4d6f00-6c41-11eb-923b-f5c3eb019c16.png)

**Comment by MariyaSha** [comment]
Thank you so much cyberblitz! I'll be revising the code later on today, as many people ran into issues with line 74. Will definitely try your solution at the same time as you're saving me lots of typing! ;)

**Comment by MariyaSha** [comment]
Thank you so much for your help cyberblitz, I've just updated the code with your wonderful suggestion! (and included you in the Thank you notes on the Readme 😉)

**Comment by cyberblitz** [comment]
No problem. I realise my indentation was not correct but glad you worked it out
